#!/usr/bin/env bash
# Change the outputs of 4th, 9th and 17 iterations

((n=1))
while [ $n -le 20 ]; do

case $n in
	4)
	echo "$n"
	echo "bad luck from China"
	;;
	9)
	echo "$n"
	echo "bad luck from Japan"
	;;
	17)
	echo "$n"
	echo "bad luck from Italy"
	;;


	*)

	echo "$n"
esac
	((n++))
done
