#!/usr/bin/env bash
# Display the hours from 0 to 12 and minutes from 1 to 59

((h=0))
while [ $h -le 12 ]; do
	echo "Hour: $h"

	((m=1))
	while [ $m -le 59 ]; do
		echo "$m"
		((m++))
	done

	((h++))
done
