#!/usr/bin/env bash
# To file or not

if [ -e school ]; then
	echo "school file exists"

	#Check school file exists or not
	if [ -s school ]; then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	#Check regular file
	if [ -f school ]; then
		echo "school is a regular file"
	fi
#File does not exist
else 	
	echo "school file does not exist"
fi
